services:
  backend:
    container_name: yoda_backend_v2
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    volumes:
      - ./backend:/app
    environment:
      - ENV=development

  frontend:
    container_name: yoda_frontend_v2
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npm config set strict-ssl false && npm install && npm run dev"
    ports:
      - "3010:3010"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8010/api
    depends_on:
      - backend
